{"uuid": "c1e70397-cbd3-41ad-a3c2-50dc489cdb37", "children": ["74b9a237-e6f2-4d72-817e-3c5c5ea887e6", "9d26b63e-c5d3-4aef-b44d-6f68318bab89"], "befores": [{"name": "login", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'F:\\\\framePytest\\\\Data\\\\login_test.yaml'\n", "trace": "  File \"C:\\python\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\framePytest\\Testcase_Api\\conftest.py\", line 8, in login\n    Authorization().update_header()\n  File \"D:\\framePytest\\Testcase_Api\\login.py\", line 28, in __init__\n    self.yaml=read_yaml().read_yaml(r\"F:\\framePytest\\Data\\login_test.yaml\")\n  File \"D:\\framePytest\\Untlis\\public\\ReadYaml.py\", line 13, in read_yaml\n    with open(r'{}'.format(path), \"r+\", encoding=\"utf-8\") as f:\n"}, "start": 1670336375201, "stop": 1670336375201}], "start": 1670336375201, "stop": 1670336375300}