{"name": "11", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "self = <Testcase_Api.test_login.Test_demo object at 0x000001C3B583ED60>\n\n    @allure.title(\"11\")\n    def test_01(self):\n        logging.info(\"info in test_func...\")\n        logging.warning(\"warnning in test_func...\")\n        logging.error(\"this is error\")\n        print(\"print console in test_func...\")\n>       assert 1 == 2\nE       assert 1 == 2\n\nTestcase_Api\\test_login.py:42: AssertionError"}, "attachments": [{"name": "log", "source": "2c894384-9c83-4b5a-a1c9-d4e46b06e84f-attachment.txt", "type": "text/plain"}], "start": 1670309719552, "stop": 1670309719553, "uuid": "df5e07f5-6e7f-458d-9b76-7d3ce80d3dd1", "historyId": "1241305104c10e36e4155af842889fc6", "testCaseId": "3c8dd7b150dc7211905cdc82414dc70e", "fullName": "Testcase_Api.test_login.Test_demo#test_01", "labels": [{"name": "parentSuite", "value": "Testcase_Api"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_demo"}, {"name": "host", "value": "MS-ULWOYCQPHOQZ"}, {"name": "thread", "value": "14524-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Testcase_Api.test_login"}]}