{"name": "我是cate的第一条用例!", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'F:\\\\framePytest\\\\Data\\\\login_test.yaml'", "trace": "@pytest.fixture(scope=\"package\")\n    def login():\n>       Authorization().update_header()\n\nTestcase_Api\\conftest.py:8: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nTestcase_Api\\login.py:28: in __init__\n    self.yaml=read_yaml().read_yaml(r\"F:\\framePytest\\Data\\login_test.yaml\")\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <Untlis.public.ReadYaml.read_yaml object at 0x00000163E9E6F160>\npath = 'F:\\\\framePytest\\\\Data\\\\login_test.yaml'\n\n    def read_yaml(self,path):\n>       with open(r'{}'.format(path), \"r+\", encoding=\"utf-8\") as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'F:\\\\framePytest\\\\Data\\\\login_test.yaml'\n\nUntlis\\public\\ReadYaml.py:13: FileNotFoundError"}, "start": 1670336375201, "stop": 1670336375201, "uuid": "74b9a237-e6f2-4d72-817e-3c5c5ea887e6", "historyId": "724e4684e113849e554d4c3b9b217c76", "testCaseId": "b75e164bf3b7287d462109c9a3cda17e", "fullName": "Testcase_Api.Shop.test_cate#test_01", "labels": [{"name": "parentSuite", "value": "Testcase_Api.Shop"}, {"name": "suite", "value": "test_cate"}, {"name": "host", "value": "LAPTOP-1IKMED1I"}, {"name": "thread", "value": "24224-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Testcase_Api.Shop.test_cate"}]}